### ISSUE TITLE
need half sized version of clocked

### ISSUE THREAD

**Issue by ghost** [MarcBoule/ImpromptuModular#1]
I loved Clocked!  But its too big.  If we could get one that is half the width maybe with less features that would be cool.  The main thing needed is the master tempo and the clock outputs with the divide multiply settings.  Who knows maybe we can even get a few extra clock outs this way?

**Comment by MarcBoule** [comment]
I had started to design a layout for this, but with so many modules to make it kind of got pushed to the side. You're not the first person to mention this though, and I'll keep your issue open until I can get to it. Thanks for the suggestions! :-)

**Comment by MarcBoule** [comment]
Better late then never :-) 
10 HP instead of 20 HP for Clocked, so it's half the size.
Should be ready for testing soon, if ever you are still interested please let me know.

![image](https://user-images.githubusercontent.com/33604154/73860343-6b47e200-4809-11ea-9b5d-546e3c76c3d6.png)

**Comment by Eurikon** [comment]
Lovely Marc, this tiny fellow will be very useful!

**Comment by ghost** [comment]
Cool

**Comment by MarcBoule** [comment]
Now released in v.1.1.4 :-)
