### ISSUE TITLE
CLKD as expander

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/ImpromptuModular#11]
Hi Marc! It seems cool to copy more than one instance of clkd across all the patch to achieve fast access to dividers and multipliers. But if this would be an expander, I mean let's make the Master instance a far left one and expanders would be placed to the right sharing bpm, reset and run triggers to each right instance...what do you think about it? 
Another mini suggestion - could you add reset both for start and stop option? Some modules work ok with start, some from stop so I'd think about both at once. I used it before in ZZC clock module by the way (this module has a huge amount of right click options and I also think they are pretty useful for the different kind of situations in the patch, maybe you would find the place in your clock for them btw).

**Comment by MarcBoule** [comment]
Thanks Artem, that first suggestion has been made by others as well, and it's on my list :-)
I'll take a look also for the reset suggestion a bit later also.

**Comment by MarcBoule** [comment]
I implemented the reset suggestion, and we now have more control over what happens during a reset. If you want to test it, it would be very much appreciated!

![image](https://user-images.githubusercontent.com/33604154/77226383-5c658680-6b4e-11ea-8923-0c7f455f1db4.png)

**Comment by MarcBoule** [comment]
Clock linking through the expander mechanism will probably not be pursued, the autoconnect idea from issue #20 being preferrable in my opinion.
