### ISSUE TITLE
PART filtering suggestion

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/ImpromptuModular#12]
Hi again Marc! How cool the Part module is! I would like to suggest some kind of enhancement to this - what if you could apply some filtering option in right click instead strong separation (that would of course stay at the default state of this module)? For example look at this screenshot. The first additional option would keep all incoming gates for HIGH output at any value of the split knob but the split knob would affect the range of incoming notes for LOW output, so it would filtering them out according the value of split knob. And the second additional option would do the vice versa things - keep all gates for low but filtering for high. This may be useful for make a specific accent for specific range of notes or one note and for sound design things of course. Do you like that idea?) Just got an instant one (as always haha).

**Comment by MarcBoule** [comment]
In this case it's probably best to just route the full gate to the destination and simply not use the output that we want to always keep all gates. Between routing live and changing menu options live, not a huge difference, but I'll think about it :-)

**Comment by MarcBoule** [comment]
After some thought, I don't think I want to add this; from the outside, the module would appear to behave quite strangely when we are not aware (or can't see) the option, so to do it properly it would have to be on the panel, but for now I don't think I want to change the design. Thanks for the idea anyways!
