### ISSUE TITLE
4view - convert incoming poly chord\notes into (expanded or not) chord-key module

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/ImpromptuModular#13]
Hi Marc! I'm here with another crazy idea. For example I have poly sample n hold module (3 voice) and I send this cable to 4view. The next thing I want to do is to record some good chords that I get from it into chord-key module without inputting it manually, just instantly by command or button, whatever. So the question - is this possible or pretty hard or not pretty much useful to do? It sounds like reverse expanding or so...or even using fetch command as in Eqmaster to catch the chord from specific 4view instance. Just an idea as always, I don't realize how it should be going technically) But it seems to me as a pretty fun way to record incoming chords for building nice chord progression into chord-key module of course with further possible changes in the module itself.  I gonna show people a manual way to copy values in my monday's video because it's kinda interesting to catch some random values, analyzing it and make a decision to save it or not. Curious what do you think on it) Cheers!

**Comment by MarcBoule** [comment]
Not sure I want to get into the fetching-type thing, but what could be possible would be to add just a "Copy chord/notes" menu entry in FourView, and then we could use the paste that is already there in ChordKey's menu. ChordKey would have to be changed to use the clipboard for the copy/paste, since it does not use it now, but it could be a neat solution. Might leave this might be for the next update though, after I think more about it.

**Comment by MarcBoule** [comment]
Ok, one more improvement that has been done! FourView also has a Portable sequence copy, so it should be quite easy to get notes from FourView into ChordKey.

![image](https://user-images.githubusercontent.com/33604154/77375240-4b319b00-6d43-11ea-93e0-b6884dde238b.png)

**Comment by vcvrackideas** [comment]
Thanks! That's working. But when I copy chord from chord key and 4view to another module with portable sequence (in this case SEQ++) I've got sequence with 4th notes instead of chord.
![2020-03-24_11-27-10](https://user-images.githubusercontent.com/42435368/77408182-61356f00-6dc8-11ea-83a9-82303c7bc0ba.png)

**Comment by MarcBoule** [comment]
Hmm, I'll have to think about this, since if I make the change, then when pasting in non-timeline sequencers like all my PhraseSeqs, all those notes will overwrite each other and there will be only one note in my sequencers.

**Comment by vcvrackideas** [comment]
Maybe two option - one copy as a chord for timeline and another - copy as a sequence?

**Comment by MarcBoule** [comment]
Exactly what I was thinking :-)

**Comment by MarcBoule** [comment]
Ok, this has been added, there are now two choices to copy for the two cases described :-) 
(the same thing was also done in ChordKey)
