### ISSUE TITLE
Undefined symbol: osdialog_filters_parse

### ISSUE THREAD

**Issue by marcoose777** [MarcBoule/ImpromptuModular#14]
When updating the plugin no longer loads at vcvrack startup, and throws an error sparking an infinite update loop.
The log reveals:
[0.041 warn] Failed to load library /home/[USER]/.Rack/plugins/ImpromptuModular/plugin.so: /home/[USER]/.Rack/plugins/ImpromptuModular/plugin.so: undefined symbol: osdialog_filters_parse

Investigating your source code with grep I find the line that causes the barf: 
./MidiFileModule.cpp:124:		osdialog_filters *filters = osdialog_filters_parse("Midi File (.mid):mid;Text File (.txt):txt");

One of the includes (#include "osdialog.h") appears to reference a file that isn't included in your repository. If it's external then it needs to be correctly referenced with filepath/scope.

**Comment by MarcBoule** [comment]
Thanks for reporting this. Are you compiling the plugin, or is it the one from the plugin manage? If you're compiling, are you compiling against the latest Rack 0.6.2b, or the latest 0.6.2b SDK?

**Comment by MarcBoule** [comment]
Now I'm confused! I'll keep my last commit with the makefile flag modification, and if ever you still have a problem, just open a new issue referencing this one, and we'll keep at it! Cheers!

**Comment by MarcBoule** [comment]
Actually, scratch that, the proper path is already in plugin.mk, line 13, which itself is included at the end of my makefile (line 27). So I'll revert the commit. It should really work as it was before.

**Comment by marcoose777** [comment]
Sorry for delay, busy at work. Thanks

**Comment by federicoweber** [comment]
Hi Marc, I'm getting the same error, installing it from the plugin manager.

Please let me know if I can provide any other pieces of information that could help to debug this.

**Comment by MarcBoule** [comment]
Are you sure you are using the lastest version of Rack (0.6.2b)?

**Comment by federicoweber** [comment]
You are right, sorry about that. I installed it from AUR and didn't notice the version was not the latest one. Working as expected with the correct version.

**Comment by MarcBoule** [comment]
Awesome! Cheers :-)
