### ISSUE TITLE
4view thru outputs don't work when the module in expander mode

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/ImpromptuModular#14]
...and maybe you didn't even plan to do that. But they can really works as a poly splitter without adding an additional one when CHORD-key in polyphonic mode

**Comment by MarcBoule** [comment]
That was a documented behavior 
https://github.com/MarcBoule/ImpromptuModular#fourview-
but I can take a look to adding it, since it does seem to make sense as you suggest.

**Comment by MarcBoule** [comment]
I made the change, ready to be tested whenever you like.

![image](https://user-images.githubusercontent.com/33604154/77239014-3373de80-6bac-11ea-8829-8f0abea37374.png)
