### ISSUE TITLE
CHD-X as a separate module

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/ImpromptuModular#16]
...for example for using with all poly sequencers (seq++, entrian or so)  to follow 3rd already written chord progression. The idea and result with CHD-X as an expander was so good and inspired as well so...
By the way I've also seen Bruce from Squinky labs also looking for that kind of quantizer

**Comment by MarcBoule** [comment]
I'm not sure I follow you, if CHD-X is used as a separate module, what does it quantize to? For what it's worth, currently when used as a separate module, it already quantizes to the 12 notes of the chromatic scale.

**Comment by vcvrackideas** [comment]
I meant with the additional poly CV input somewhere in the panel.

**Comment by MarcBoule** [comment]
I think it would go too far beyond the current mandate of the module, and I don't think I'm ready to go there with this design. This would ideally be better done as another module.
