### ISSUE TITLE
Text label positioning in dark extended Clocked

### ISSUE THREAD

**Issue by lnikj** [MarcBoule/ImpromptuModular#17]
HI Marc

Spotted this this morning:

![screenshot_109](https://user-images.githubusercontent.com/24451110/45141679-79c24200-b1ae-11e8-8335-fc604dbb4676.png)

Cheers

Nik

**Comment by MarcBoule** [comment]
Hi Nik,
Thanks for the report. It was indeed an oversight in the last update, but it has been fixed for the next release (0.6.11). Cheers!
Marc

**Comment by lnikj** [comment]
Thanks Marc!
