### ISSUE TITLE
Tact Feature Request

### ISSUE THREAD

**Issue by Telerex** [MarcBoule/ImpromptuModular#18]
Tact/Tact1 are by far my favourite controllers in VCV and I have used it as the front end for whole synth layouts. 
There are still a couple of things I think could make them even better.
1) Auto return to zero or even the stored voltage upon release of the mouse button (at the rate speed) giving the ability to return to a starting point after a heavy bout of  mouse wiggling. Recall is good but this gives another option for reset
2) Pitch Bend mode +-5v with the centre as starting point. Individually selectable to give us that classic pitch bend/modulation wheel combo.
Having these options in the menu so as not to spoil the already great design of the modules.
I would love to see these features added if possible and I'm sure others could find a use for them.
Thanks.

**Comment by MarcBoule** [comment]
Thanks, at first glance those look like neat suggestions, I'll see what it looks like implementation-wise, and I will consider it. Cheers!

**Comment by MarcBoule** [comment]
I have added an Auto-return option, which I think should hopefully cover many useful cases. If ever you want to test it, please let me know your platform and I'll put up a build in the release section. Thanks!

![image](https://user-images.githubusercontent.com/33604154/85201093-a8010b00-b2ca-11ea-9492-a005e7ba51ae.png)

**Comment by Telerex** [comment]
That sounds great. Do the lights indicate the setting and follow from there?

**Comment by MarcBoule** [comment]
Yes, when we choose, for example, 80% in the menu, the tact pad will automatically go to 80% and then when we click-drag the pad, it will change to that value at the speed given by the current rate, and then when we release the mouse, it will go back to 80% at the current rate.

**Comment by MarcBoule** [comment]
This is now released, closing.
