### ISSUE TITLE
Write-SEQ Sequence offset/rotate

### ISSUE THREAD

**Issue by TroyArt2020** [MarcBoule/ImpromptuModular#19]
I often use quantized noise as the CV IN to generate random sequences which works great, however this often results in the sequence being "out of sync" with my drums or other sequences. It'd be nice to rotate the entire sequence left/right one step at a time:

```
Current sequence:                 C1 C2 C3 C4
After pressing rotate right once: C4 C1 C2 C3
```

**Comment by MarcBoule** [comment]
Hi, the WriteSeq sequencers don't offer the rotate feature, but if you like, you can try PhraseSeq16, PhraseSeq32 or Foundry, which do have this feature.
I'm not sure I want to change the panel to add this feature to the WriteSeqs though, perhaps in the menu, but I'll have to think about it more. Cheers!

**Comment by TroyArt2020** [comment]
Didn't realize PhraseSeq had rotate, I'll try that out!

In regards to not wanting to change the panel, perhaps a right-click menu option such as "Arrow Controls" with sub-menu options "Step" and "Rotate", with "Step" being default.

**Comment by MarcBoule** [comment]
I just added the option, if ever you want to test it, please let me know what platfrom you use and I'll post a build. Thanks!

**Comment by MarcBoule** [comment]
This is now released, closing.
