### ISSUE TITLE
why was the repo nuked?

### ISSUE THREAD

**Issue by Skrylar** [MarcBoule/ImpromptuModular#2]
To get rid of the pre-GPL stuff?

**Comment by MarcBoule** [comment]
No, it was nuked to reduce its size. I had a post up for many months asking for help with this, and after trying a few different methonds, cloning it was still downloading too much data, so the only option I could find was to restart the repo. I know this is probably a github sin, but I like to keep things lean. I did the same with Geodesics. 

I have archives of the repos before the nuke, in case anyone wants them. For the record, I even offered them to the creator of MiRack, so the goal was not to hide the pre-gpl stuff.
