### ISSUE TITLE
Tact Auto-return to up and down CV input as well

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/ImpromptuModular#22]
Hi Marc! It would be awesome if you will add Auto-return action to up and down cv inputs for triggers as well. As I can see it reacts now only on mouse, so I'd like to map numpad for example via midi-gate right into the up and down triggers without messing with midi mapping which is working solution now. Cheers!

**Comment by MarcBoule** [comment]
Nice idea, I forgot about those inputs. It has now been added. Thanks as always Artem :-)

**Comment by MarcBoule** [comment]
This is now released, closing.
