### ISSUE TITLE
Does not compiled on Windows 10 Pro

### ISSUE THREAD

**Issue by caecos** [MarcBoule/ImpromptuModular#22]
H_DEFINES -c -o build/src/GateSeq64.cpp.o src/GateSeq64.cpp
src/GateSeq64.cpp:136:2: error: 'BooleanTrigger' does not name a type
  BooleanTrigger editingSequenceTrigger;
  ^~~~~~~~~~~~~~
src/GateSeq64.cpp: In member function 'virtual void GateSeq64::step()':
src/GateSeq64.cpp:514:8: error: 'editingSequenceTrigger' was not declared in this scope
    if (editingSequenceTrigger.process(editingSequence))
        ^~~~~~~~~~~~~~~~~~~~~~
src/GateSeq64.cpp:514:8: note: suggested alternative: 'editingSequence'
    if (editingSequenceTrigger.process(editingSequence))
        ^~~~~~~~~~~~~~~~~~~~~~
        editingSequence
make: *** [../../compile.mk:65: build/src/GateSeq64.cpp.o] Error 1

**Comment by caecos** [comment]
J’ai recompilé Rack et tout fonctionne…

Merci,

Marc

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Marc Boulé <notifications@github.com>
Envoyé : Sunday, November 25, 2018 7:54:47 AM
À : MarcBoule/ImpromptuModular
Cc : caecos; Author
Objet : Re: [MarcBoule/ImpromptuModular] Does not compiled on Windows 10 Pro (#22)


Make sure you are using the lastest sources/SDK of Rack, this error happens when using older versions before BooleanTrigger was added by Andrew.

**Comment by MarcBoule** [comment]
Super! Content de voir que ça marche.
Salutations,
Marc
