### ISSUE TITLE
next pattern trig input

### ISSUE THREAD

**Issue by joopvdl** [MarcBoule/ImpromptuModular#23]
I know there's probably no room left, but a trig input for "next pattern" on the sequencers would make pattern management so much easier.

**Comment by MarcBoule** [comment]
Another way would be to have a right click option to allow the user to choose how the SEQ jack behaves, thereby not requiring an extra jack in the expansion panel. Will think it over, but I will definitely implement it one way or another...

**Comment by joopvdl** [comment]
I think the side panel will be most useful. So you have different options
on seq selection.
I'm on Windows.
Looking forward to doing some testing!

btw, another suggestion: would be interesting to look at a way to program
trigseq patterns thru midi. Like mapping them to a range of midi notes, or
possibly there's an easier way. Would make for some pretty fast programming
:)
thanks! Joop

**Comment by joopvdl** [comment]
Hey Marc!
Yes, I would very much like to try that out!
I'll be home in about 10 hours or so, see you on Facebook.

cheers, Joop

Op do 6 dec. 2018 om 03:23 schreef Marc Boulé <notifications@github.com>:

**Comment by MarcBoule** [comment]
Done in 0.6.13, which is now released. Thanks Joop!

**Comment by joopvdl** [comment]
glad to help!
