### ISSUE TITLE
clocked modulation of clock speeds?

### ISSUE THREAD

**Issue by ghost** [MarcBoule/ImpromptuModular#25]
Hi can this be done for the clock outs 1-3?  Its useful for gate triggers!  I can do it with lfos just thought is would be simpler.

**Comment by ghost** [comment]
never mind I forgot I have umap - sorry

**Comment by MarcBoule** [comment]
Yes, I think uMap will have to be the way to go, since I don't think I will add CV inputs for the clock ratios. Cheers!
