### ISSUE TITLE
TactG don't interrupt chain gate input feature request

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/ImpromptuModular#27]
Hi Marc! I have a feature request on this function, I mean it would be useful when I set up all of my parameters and then connect a sequencer to the last added chain input and then try to adjust CV controls on previous Tacts so the sequencer's gate wouldn't be interrupted when tact like was been touched. I feel it would be nice to have it as an option in right click menu. Cheers!

**Comment by MarcBoule** [comment]
Just to make sure I understand, it would be a gate-bypass option such that its chain gate-in would still pass through unaffected, but the TactG would not emit its own gate?
