### ISSUE TITLE
Mouse painting on the GATE-SEQ-64?

### ISSUE THREAD

**Issue by Skrylar** [MarcBoule/ImpromptuModular#27]
First, I love your modules :+1: 

It would be nifty if click+drag across the sequencing pips would set them to active (ex. like the trowaSoft trigSeqs and FL Studio drum entry, etc), and doing the same with the right mouse button would set them to inactive (as RMB does to a lot of controls in Rack.) Having to double-click to remove pips one by one seems a little wrist and mouse heavy.

**Comment by MarcBoule** [comment]
The right-click is definitely interesting, and should be straight-forward to implement, so that's definitely a something I will look to add. For the click+drag, it might be more work, but I'll take a look. Thanks for the suggestions :-) Cheers!

**Comment by Skrylar** [comment]
Just spitballing here, since I haven't peeked inside the code yet:

- A painting mode enum (idle, setting, deleting) to track what the mouse is doing
- Left clicking in a gate sets it to "setting" and sets it
- Mouse movement over the gate while in "setting" mode also sets it
- Right clicking sets it to "deleting" and deletes it
- Mouse movement over the gate while in "deleting" mode also deletes it
- Raising the mouse button sets it back to idle
- Movement over the module where neither button is pressed also sets it to idle

What I don't know about the plugins yet (since I've mostly been doing I/O work with it) is if we have a simple "mouse exit" type event, or have to try and be more clever like testing for the mouse hovering over other stuff in the module without a button held down.

**Comment by Skrylar** [comment]
Unfortunately, the build is broken :worried: 

```
src/GateSeq64.cpp:137:2: error: ‘BooleanTrigger’ does not name a type
  BooleanTrigger editingSequenceTrigger;
```

**Comment by Skrylar** [comment]
```
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[b7243de361b1429dcf95580d332a0707e8db8915] Code clean and refactor PS,GS,SMS
```
Is the commit which breaks the build, between `0.6.10` and `cfe6db8983deb795ea2514e68bfcfc4e0a052fff`

**Comment by MarcBoule** [comment]
You have to get the lastest SDK or Rack source.
https://github.com/MarcBoule/ImpromptuModular/issues/26

**Comment by Skrylar** [comment]
The latest SDK is what I used (https://github.com/VCVRack/Rack/issues/258), and the error happens. It seems unreleased APIs are afoot :wink: 

RMB confirmed working (on a Rack `master` build) on Linux :+1:

**Comment by MarcBoule** [comment]
I have implemented mouse painting in GateSeq64, in the v1 branch only since I'm no longer developing in the 0.6.x. I had to change the clicking strategy to make  mouse painting work well and also since right-click has changed in v1 (I no longer use it). 

@Skrylar : If ever you are testing v1 and get a chance to play with it, please let me know of any issues or comments.
