### ISSUE TITLE
TactG - feature request on visualizing external offset control

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/ImpromptuModular#28]
Hi again Marc! I curious would it be possible to apply some visualization to the visual strip of Tact to show how external offset CV affects on overall sending voltage? Cheers!

**Comment by MarcBoule** [comment]
If I think of a good way to do it in the current scheme, I'll come back to this request, but like my other comment in issue #29 I want to stick with the current minimalistic and near-hardware look using lights, buttons and knobs, so in the current package there's no easy way to add more visuals. Great ideas though, thanks for mentioning it :-)
