### ISSUE TITLE
TactG - label name strip like in on mindmeld mixer ;-)

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/ImpromptuModular#29]
Marc, since Tact-G becomes for me a very useful thing for some kind of controlling things I'm curious if you would like to change (optionally) a label strip instead of beautiful Tact-G logo (again not always, via switching in context menu). I understand we have Stoermelder glue for that but I'd personally like to have a built-in thing. Cheers!

**Comment by MarcBoule** [comment]
Hi Artem, although I could make this using some of those labels like we have in MindMeld, I think it does not fit with the Impromptu style of being more minimalist and closer to pure hardware (kind of like Geodesics also). So unfortunately for design style consistency reasons I don't think I want to implement this. Thanks, and cheers!
