### ISSUE TITLE
gate seq midi programming

### ISSUE THREAD

**Issue by joopvdl** [MarcBoule/ImpromptuModular#3]
Hey Marc,

Some time ago, we discussed options for the gateseq, and I remember suggesting a programming mode where midi notes would enable/disable triggers, thus creating a quick way to program the sequencer (and playing it live). For instance, I have a monome grid, and I could use that to program drum patterns on the fly.
I tried looking up those discussions, but it seems you have cleaned up this repo. 
Anyway, would you be interested in some more thinking about this? 

Joop

**Comment by MarcBoule** [comment]
Hi Joop, long time no talk :-) 
I did clean up the repo, but I kept that whole discussion as a reference for when I would get to the new gate seq project. Things are very busy around here, and I fear that being a developer for three module packs has distilled my time away from big projects in Impromptu. So given what I have in the pipeline for Geodesics and MindMeld, I don't think I will be getting to the new gate seq very soon unfortunately. Latif is also waiting for this one and was also participating in the discussions, and offered to contribute more suggestions for when we get to it. I think I will have to clone myself! ;-)
Take care,
Marc

**Comment by MarcBoule** [comment]
Dropping the archived discussion here for reference:

[[enhancement] Gate SEQ 64 · Issue #13 · MarcBoule_ImpromptuModular.pdf](https://github.com/MarcBoule/ImpromptuModular/files/4022483/enhancement.Gate.SEQ.64.Issue.13.MarcBoule_ImpromptuModular.pdf)

**Comment by joopvdl** [comment]
Yeah, you're already spoiling us with great stuff, I know :)


Op za 4 jan. 2020 om 21:59 schreef Marc Boulé <notifications@github.com>:
