### ISSUE TITLE
Copy paste 8 steps option in PS16

### ISSUE THREAD

**Issue by MarcBoule** [MarcBoule/ImpromptuModular#3]
As suggested to me in private FB message from Xavier Belmont, the idea of copy-pasting blocks of 8 steps could be a useful enhancement.

If it can be done while preserving the aesthetics of the module, it will definitely be considered, as I personally can appreciate the usefulness of this possibility. Perhaps in a first attempt that would be a good compromise of functioanlity vs faceplate real-estate, a single button copy-paste operation that would automatically duplicate the first 8 steps into the second 8 steps might do the trick. Noted, and thanks for the suggestion Xavier!

**Comment by XavierBELMONT** [comment]
Thanks Marc, 
What would be great is to be able to copy 8 steps (maybe choosen by the "cursor" position in the "attach" mode off) and to paste them in the same or other sequence after moving this cursor where we want the 8 copied steps to be paste...    ...as long as we stay with the 8steps value, there's no need to put on too many extra controls I think, but I'm maybe wrong, anyway great seq!

**Comment by MarcBoule** [comment]
Upon further thought, I think this will be best left as an option on a bigger Phrase-Seq-32 or 64, since as it is now, with the new tied step light and layout adjustment, I am not finding a good was to add extra buttons. With only 16 steps, it may not after-all be a big drawback to not have the copy/paste 8 steps option, even though it would indeed come in handy. Here's the current look of the next version (0.6.4), which I think will be about as much as I feel comfortable having on the module's face-plate. 
![image](https://user-images.githubusercontent.com/33604154/39666225-438caeba-506e-11e8-8863-57d43f077dda.png)
