### ISSUE TITLE
Feature Request: 2 PPQN

### ISSUE THREAD

**Issue by cschol** [MarcBoule/ImpromptuModular#30]
Some hardware devices, for example the [Volca Sample](https://www.korg.com/us/products/dj/volca_sample/), use a 2 PPQN sync signal. The Beatstep Pro controller supports that in its latest firmware and syncing with the Sample works great.

I would like to use Clocked via an Expert Sleepers ES-8 DC-coupled interface to clock the Volca Sample, but it would need to support 2 PPQN. Thanks!

**Comment by MarcBoule** [comment]
I added a 2 PPQN and 16 PPQN setting to Clocked. Thanks for the suggestion, and thanks for all those code reviews Chrisoph, much appreciated! I'll likely be requesting an update very soon :-)

**Comment by cschol** [comment]
Wow! Awesome. Thank you so much, Marc. I LOVE your module pack and use especially the sequencers all the time even with real Eurorack hardware.

**Comment by MarcBoule** [comment]
New version with new ppqns is now in plugin manager, closing issue.
