### ISSUE TITLE
Slide broken in PhraseSeq16/32 and SMS16

### ISSUE THREAD

**Issue by MarcBoule** [MarcBoule/ImpromptuModular#31]
This has been fixed in the code, and will be part of the upcoming 0.6.15 release. Mac and Win builds are in the releases section, for those that want to try it out before it gets to the plugin manager.

**Comment by NRG70** [comment]
Oh it was broken on your side,  I did notice it when I was testing Interzone. But thought it was the synth not reacting to slide, duh.
Should have let you known. 
Thanks for fixing!

**Comment by MarcBoule** [comment]
New version with bug fix is now in plugin manager, closing issue.
