### ISSUE TITLE
feature request: gates off while run off

### ISSUE THREAD

**Issue by glocke01** [MarcBoule/ImpromptuModular#33]
I'd like to request an additional right-click menu option that would zero out all the clock gate outputs (excluding reset) while run is off. I think this might help with sync'ing sequencers to the clock.

**Comment by MarcBoule** [comment]
I think you can already get something similar to what you are asking, by setting the following options in Clocked/Clkd:

![image](https://user-images.githubusercontent.com/33604154/104032373-15f41d80-519c-11eb-80ff-6c5b4ea94290.png)

Turn off "Ouputs reset high when not running" and turn on "On Stop -> Do internal reset", and it should do the trick.

**Comment by glocke01** [comment]
thanks! that does it!!
