### ISSUE TITLE
2 PPQN is not saved due to clamping

### ISSUE THREAD

**Issue by cschol** [MarcBoule/ImpromptuModular#33]
The new 2 PPQN value is not saved due to clamping (to value 4) in the settings save:

```
// ppqn
json_t *ppqnJ = json_object_get(rootJ, "ppqn");
if (ppqnJ)
	ppqn = clamp(json_integer_value(ppqnJ), 4, 24);
```

**Comment by MarcBoule** [comment]
Didn't see that one. Sorry, fixed now; there is no reason to clamp that anyways, don't know why that was there.

I'll wait a week or two before updating if that's ok, don't want to abuse the review/build process! :-) Thanks!

**Comment by MarcBoule** [comment]
Fixed version now in plugin manager, thanks @cschol !

**Comment by cschol** [comment]
Thank you!
