### ISSUE TITLE
Accept polyphonic CV input, and output that recorded polyphonic CV in sequencers

### ISSUE THREAD

**Issue by ohechtl** [MarcBoule/ImpromptuModular#36]
I'm trying to find a great polyphonic recording and output capable sequencer in VCV Rack, which could record polyphonic sequences from my Arturia KeyStep. I've checked Foundry, PhraseSeq and BigButtonSeq, but I've found out that they only output monophonic CV.

What is your opinion about this? Could this be a good addition to the Impromptu sequencers? 

I know that Foundry can output 4voice poly CV with it's four channels, but what if I want more polyphony?

Until now, I've used a piano roll from Ableton outputted to a loopMidi loopback and sequenced my synths with that, but it'd be super fun to have this functionality in VCV Rack, modular style.

**Comment by MarcBoule** [comment]
In general the sequencers I have to far in Impromptu are not really geared towards polyphony, with the very small exception of merging up to 4 track in Foundry. I don't think general polyphony can be added cleanly in the current sequencers, as ideally we would need to be able to edit all channels in the poly signal, so I think this will be best kept for another sequencer I have been planning that would be built from the ground up to better cater to polyphony. Unfortunately it will take a while for me to get to that project, so in the mean time if you really want to get polyphonic sequencing in Rack, my suggestions would be to try out Seq++ by SquinkyLabs, or the Entrian sequencers. I think both of those even support Midi. Cheers!

**Comment by ohechtl** [comment]
Thank you Marc for the quick reply. Thanks for all the awesome modules nonetheless, and now you made me excited about that polyphonic sequencer you planning to create :) 

I'll check out those you mentioned.

Thanks!

**Comment by MarcBoule** [comment]
My pleasure, enjoy the modules :-)
