### ISSUE TITLE
sequencers proposal

### ISSUE THREAD

**Issue by NRG70** [MarcBoule/ImpromptuModular#37]
Gate sequencers & Phrase sequencers 
could have the built-in clock multipliers also as halver (ie: x2 as /2), 
this would eliminate the need for multiple or too many Clocked modules in a patch.

why? 
sometimes when the clocked module is used with all its outputs 
example: 
base clock 1:  x1
clock 2:   x 1 delayed 1/8
clock 3:   x 6 delayed 1/8t
clock 4:   x 1,5 delayed 1/8t

Now i would need a clock signal x4 for something else.
This means i have to open a new Clocked module, 
for me no problem in VCV, but in real world $$$ :D

So alternatively i could use a clock multiplier 
(rarely can find a good one or one that is actually steady/stable).
I have one from Klirrfactory, it is the best multiplier.
However, when i use this one, the (gate) sequencers will not start in time, all of the time.

So my proposal: add clock division to the already built-in clock multiplier in the sequencers.
Or sequence mult/div cause i don't know exactly the structure inside your machines, 
whether you manipulate the incoming clock, or the playback of the sequences them-self.

cheers :)

**Comment by MarcBoule** [comment]
Hi Latif, I'm catching up on some discussions here while I'm working on the layout of the new Foundry-like gate sequencer, and regarding internal clock multiplication, I think I will avoid adding that functionality, to keep things focused. I prefer to do a little less things but do them well (I hope), and in this case I would defer to the modular paradigm that if an external module can do it (and it does it well), then we will do it there. Now if no clock multiplier works well enough, then that could definitely be a companion module for Clocked, but that's another can of worms! Thanks for the suggestion :-)
