### ISSUE TITLE
ProbKey: polyphonic offset?

### ISSUE THREAD

**Issue by martin-lueders** [MarcBoule/ImpromptuModular#37]
Dear Marc, thanks for this great sequencer. It's really fun to work with.
I noticed only one thing, which would make it even more versatile: would it be possible to also accept polyphonic signals to the offset? 

Cheers,
Martin

**Comment by MarcBoule** [comment]
Hi Martin, good idea, I think it should be no problem to implement, I'll take a look. Thanks for mentioning it; I'm glad you like the module!
Take care,
Marc

**Comment by MarcBoule** [comment]
I have implemented the poly suggestion on Offset, pGain (which was recently changed and renamed to Density), and on Squash, so it was a great idea that can add more flexibility! Feel free to try it out if you like, it's in the **pk** branch until I deploy it. Cheers Martin!

**Comment by MarcBoule** [comment]
pushed in library
