### ISSUE TITLE
Foundry etc. sliding note: how to suppress second gate reattack?

### ISSUE THREAD

**Issue by jamshark70** [MarcBoule/ImpromptuModular#38]
I am struggling with sliding notes in Foundry.

Let's say I want to slide from C down to A.

The V/OCT slide is easy enough.

But you may also want the gate to sustain through the slide -- it is not always the case that you want the slide-to note to reattack, but rather to slur.

"Tied note" strictly enforces tying to the same pitch (no slurs).

Slurred notes are a pretty basic part of acid basslines so it's surprising to me that it isn't obvious how to do it (i.e. user-friendly).

Sorry if I'm just really dumb and overlooking it. It's very confusing. I did read the manual but I don't see it.

**Comment by jamshark70** [comment]
Aha, found it :man_facepalming: 

1. First note: Switch from note mode to gate mode and choose the sustaining gate.
2. Second note: Enable glide.

So I'll close this now -- apart from reporting that this isn't immediately evident.

Great sequencer btw!

**Comment by MarcBoule** [comment]
Ok, thanks! Yeah, it's got some quirks and is far from perfect, but glad you got it working for you :-)
