### ISSUE TITLE
Foundry 0.6.15 Entering CVs issue.

### ISSUE THREAD

**Issue by therealkitman** [MarcBoule/ImpromptuModular#38]
Hi Marc,
I have connected a midi keyboard and the Tonespace chord generator via MIDI-4 and want to program tracks A,B,C,D with a 4 note chord. I have selected all tracks (A*) and all my 4 track CV input indicators are red. 
![image](https://user-images.githubusercontent.com/14888092/53389418-3791f480-39ca-11e9-8920-1f15cdb47039.png)
However, the 4 unique notes of the chord are displayed momentarily using 4-VIEW, as the above snapshot shows, regardless of how long the WRITE input is held high by the MIDI-4 gate, then all 4 tracks are assigned the note of the 4th (last) note in the chord as shown below.
![image](https://user-images.githubusercontent.com/14888092/53389554-b5560000-39ca-11e9-9cc4-617077d67400.png)
I have to enter the notes for each track separately.
I believe my technique to be valid so is this a bug to enter notes for all tracks simultaneously?
Regards,
Chris.

**Comment by MarcBoule** [comment]
Thanks for reporting this, it is indeed a bug. I have fixed the bug and put an updated windows build in the latest release. If you are on Mac, I will post a build later when I get home. If you can test it out, it would be very much appreciated. Cheers!
https://github.com/MarcBoule/ImpromptuModular/releases/tag/0.6.15b

**Comment by therealkitman** [comment]
I'm actually a linux boy so I will compile the source tonight and test.
Thanks.

**Comment by therealkitman** [comment]
Sorry Marc, I am can't compile from source. I copied the source to ~/.Rack/plugins/ImpromptuModular-0.6.15b and ran 'make dep' as per the manual at https://vcvrack.com/manual/Building.html but I get errors. What are the steps please to compile and what if any are the dependancies?

> chris@asus-roc:\~/.Rack/plugins/ImpromptuModular-0.6.15b> make dep
Makefile:28: ../../plugin.mk: No such file or directory
make: *** No rule to make target '../../plugin.mk'.  Stop.
chris@asus-roc:~/.Rack/plugins/ImpromptuModular-0.6.15b>

**Comment by MarcBoule** [comment]
There are no dependancies required to build Impromptu. The instructions you are linking to however, are to build Rack itself, so when you clone Rack, and then `cd Rack`, it's there that you have to use those instructions, of which the `make dep` is the second command 
(the first being `git submodule update --init --recursive`).

When you have Rack built, then from the `Rack` directory, you should do this to build Impromptu:
````
cd plugins
git clone https://github.com/MarcBoule/ImpromptuModular.git
cd ImpromptuModular
make -j8
```

I'll try to build a Linux version tonight for you if you don't want to mess with compiling. I took a chance that you were on Mac/Win, but it's no problem to add a Linux version also in the releases section.

**Comment by therealkitman** [comment]
Thanks Marc, appreciate you doing the linux version (saves me a lot of grief compiling :) ).

Yes, your patch has fixed the bug, all 4 tracks a retaining the notes as recorded via midi. 

However, I had an issue where - 
> [0.049 warn src/plugin.cpp:90] Failed to load library /home/chris/.Rack/plugins/ImpromptuModularbeta/plugin.so: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/chris/.Rack/plugins/ImpromptuModularbeta/plugin.so)

My OS is openSUSE leap15.0 has the glibc 2.26 as it's official release. Your plugins worked fine with this up to this fix. I had to use a community repo (which I hate doing) to upgrade glibc to 2.27. Will your next official release need glibc 2.27 permanently?

Thanks,
Chris.

**Comment by MarcBoule** [comment]
Hmm, I'm not too proficient with glibc requirements and how to control which version my plugin uses, but if it was working well before, I assume it's because it was being built by Andrew for the plugin manager, and he has a different setup than mine. If you know how I can change this on my end, please let me know, but perhaps we could also just a few days unitl the new version hits the plugin manager, and then you can go back to 2.26.

**Comment by therealkitman** [comment]
I was not aware that Andrew did all the plugin manager builds - man that must be some job to maintain!!!
Since the bug has been fixed I'll closed this issue and wait for it to be released via the plugin manager. There are plenty of other lovely plugins me me to learn and play with in the mean time :)
Thanks very much for the quick fix,
Chris.
PS. I'm no expert in compiling but in linux I believe you would need to set an ldflags variable with an ordered list of paths to search for libraries.
