### ISSUE TITLE
SMS16: misplaced labeling

### ISSUE THREAD

**Issue by Eurikon** [MarcBoule/ImpromptuModular#39]
Hi Marc,

i don't know whether to report V2 issues here? 

Anyway, somehow the: Reset & Clock labels for SMS 16 got switched around. 

All the best, back to testing :) 
Latif

**Comment by MarcBoule** [comment]
Oh wow! Thanks so much for catching that and reporting it :-) The gitub issues is the perfect place. 
Thanks Latif!
