### ISSUE TITLE
v2 beta of Clocked does not honor 'reset gates high when stopped' = 'OFF' setting. 

### ISSUE THREAD

**Issue by fractalgee** [MarcBoule/ImpromptuModular#40]
v2 current Rack beta and your posted beta, windows 10, latest patches

Clocked (and small sibling) do no longer honor the OFF setting of 'Gates rest high when stopped' = 'OFF' (not selected)

v1 shut down all gates with that setting active on  stopping the clock. Now clocks stay as they were.

This will break many many of my v1.x patches that rely on the gates to shut off completely, on stopping clock.
toggling setting on and off again does not fix this either, so toggling run until all gates low is only way, not too workable...

**Comment by MarcBoule** [comment]
I tested and can't reproduce your bug, and the behavior seems identical to v1. Are you sure you're not miunderstanding what "Outputs reset high when not running" means? The operative word here is "reset", meaning if you turn the clock off at a point where a clock is low, it will not automatically go high. But when that option is on, pressing reset will make the output go high, but only upon reset being pressed.

If you think there is still a problem, I will need the exact steps to reproduce, starting from a clean CLKD dropped in a patch.

**Comment by fractalgee** [comment]
Aha, found the culprit, not your clock but a missing setting: 'On Stop-> Do internal reset'. That makes it behave identical to v1 when 'reset gates to high when not running'. All working. Went to save a v1 patch with just my configured clock in it and a v2 one that wasn't behaving to find what was different (gotta love diff and friends). Closing this

**Comment by fractalgee** [comment]
I've shared an item with you:

Screen Recording 2022-01-05 at 21.44.13.mov
https://drive.google.com/file/d/1a2eusRDr3FiZeNpXFgEDLaEUepuxJ-qw/view?usp=sharing&invite=COr1wIEF&ts=61d604d6

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

Here is a small mov showing the issue. I can move them independently but  
next randomize they are back coupled
