### ISSUE TITLE
Rack v1: Slug update required for Semi-Modular Synth

### ISSUE THREAD

**Issue by cschol** [MarcBoule/ImpromptuModular#42]
Rack `v1` requires all slugs defined in the module to adhere to the [naming conventions](https://vcvrack.com/manual/PluginDevelopmentTutorial.html#naming).

Rack `v1` now also normalizes the module slugs when loading a patch, i.e. it removes all invalid characters from the module slug. That way, backwards compatibility can be achieved with pre-v1 patches. You just need to ensure that the new slug for the module matches the normalized version and Rack `v1` will find the module in the patch.

The slug for `Semi-Modular Synth` contains a whitespace character that needs to be removed. The new, normalized slug should be `Semi-ModularSynth`.

**Comment by MarcBoule** [comment]
Fixed in https://github.com/MarcBoule/ImpromptuModular/commit/56176faf54191870e30a1ebc02e9efbda10cb899
thanks! If ever you want to re-pull into the v1 library, feel free.

**Comment by cschol** [comment]
Note, that with this slug change the backwards compatibility is **NOT** working! Rack `v1` will only **remove** invalid characters, like the whitespace character in this case. It cannot **insert** a character, like the `-`.

**Comment by MarcBoule** [comment]
Oh, didn't see that little part about not breaking patches, thanks so much, will do!

**Comment by MarcBoule** [comment]
Ok, got it now (I did Geodesics also). Many thanks @cschol !

**Comment by cschol** [comment]
Perfect. Thanks!
