### ISSUE TITLE
Clocked Panel when Zoomed

### ISSUE THREAD

**Issue by midiguru** [MarcBoule/ImpromptuModular#45]
I zoomed the Rack display down to 45% and then back to 100%. The attached jpg shows the result. The Zoom slider actually has a finer response than 1%, so only _some_ slider values that show as "100%" will produce this error; other "100%" settings will look fine.
[clocked_graphics_bug.zip](https://github.com/MarcBoule/ImpromptuModular/files/3369231/clocked_graphics_bug.zip)

This is reproducible; I tried it after closing VCV Rack and re-launching, and got the same result.

--Jim Aikin (midiguru23@sbcglobal.net)

**Comment by MarcBoule** [comment]
Hi Jim, thanks for the bug report. It's an ugly bug indeed, but it's a problem with Rack that affects many other plugins also, so there really isn't anything I can do. If you want to read more about it, there is an open issue on VCV Rack's github here:

https://github.com/VCVRack/Rack/issues/1335#issuecomment-502495017

Even Andrew is stumped as to how it can be fixed, so it's a tough one :-) 

Cheers!

Marc
