### ISSUE TITLE
Light Colours (Colour Blind Accessibility)

### ISSUE THREAD

**Issue by inigokennedy** [MarcBoule/ImpromptuModular#46]
First off thank you for the amazing modules @MarcBoule 

Could I request a potential improvement to help us colour blind users; in particular red/green deficient. In the sequencer modules (PHRASE-SEQ, etc.) it is almost impossible for me, and I'm sure others, to see the difference between the gate enabled steps (green) and the selected step (red) and that makes it really tricky to know where you are at. This is really common with hardware too. It's also difficult to see the difference between the yellow and green although that is less of a frustration in general use. I wonder if there is scope for a colour blind mode or user configurable light colours? Looks like a simple change in Components.hpp to use e.g. SCHEMA_BLUE instead of SCHEMA_RED but I know the source code is pretty much baked-in with the colour names it uses as well. I think you're combing red+green to get the yellow for example too but thought it worth asking as maybe it's possible to abstract things and offer some flexibility.

**Comment by MarcBoule** [comment]
Hi, thanks for the kind words!

No problem to do this, but I didn't want to complexify the menus, so I made the green and red colors for the LEDs customizable via the `ImpromptuModular.json` settings file that gets created in the Rack user directory. So this way you can enter the exact RGB values you would like.

![image](https://user-images.githubusercontent.com/33604154/144950681-a1a9f7d6-766e-4412-9988-7efc9d685eaa.png)

Please let me know which platform you are on, and I'll prepare a build for you to test. Your file now does not look like what is shown above (if you have saved a current theme for Impromptu), but when you get the build, you will simply have to save the default theme once, and then you will see the colors, and then be able to change them.

Cheers!

**Comment by inigokennedy** [comment]
Thanks @MarcBoule for that super fast and neat solution. Kudos. I've made a build from the latest commit here and it's working really nicely (win x64). Simply flipping the RGB values in the _.json_ like below is a massive usability improvement in various of the plugins and super nice that things can tweaked to suit individual needs.

```
"redLED_RGB": [
    36,
    44,
    237
  ]
```

Cheers!

**Comment by MarcBoule** [comment]
Excellent! :-)
