### ISSUE TITLE
WriteSeqs gate should be forced low when not running

### ISSUE THREAD

**Issue by MarcBoule** [MarcBoule/ImpromptuModular#47]
Bug report: https://community.vcvrack.com/t/write-seq-64-gate-is-open-when-not-playing/4686

**Comment by MarcBoule** [comment]
Fixed in 9b185e5, will be part of the next update.

**Comment by FunkybotsEvilTwin** [comment]
I know this item is closed, but is this applicable to Clocked? I'd like to have Clocked close all gates when Run is turned off, without triggering a reset, which throws off some sequencers. So basically, a "Gates close on Run Stop" mode. Then throw in a "Reset on Run Start" and you've basically got the all the scenarios covered without having to use other modules as workarounds.

**Comment by MarcBoule** [comment]
Hi, Thanks for the suggestion, I will ponder this and get back to you, since making this sort of change without breaking patch compatibility in existing patches deserves more thought on my part. Cheers!
