### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by jpnielsen** [MarcBoule/ImpromptuModular#47]
<img width="942" alt="image" src="https://user-images.githubusercontent.com/27916597/145239173-7a34cec3-c7ee-412b-ade2-1f59ec139b16.png">

If i input a clock to Clocked "BPM", I can't have CV output - But I would like to slew rate limit the changes.

I'd like to have a module that outputs the CV that corresponds to a clock input.

Thank you.

**Comment by MarcBoule** [comment]
I'm not sure I follow your use case, since in the picture you are giving the first Clocked a BPM CV as opposed to an external clock signal. In that setup, it's BPM output is a CV for the BPM.

**Comment by jpnielsen** [comment]
Right, That picture only confuses.

Say, I have a MIDI-CV 24PPQn and i want CV clock output i can slew limit to the next clocked CV-BPM input.

**Comment by jpnielsen** [comment]
I dunno - perhaps it's a silly idea. Lets just close this again.

**Comment by MarcBoule** [comment]
Let's leave it open, I'll take a look, I think I know what you're after now.

**Comment by MarcBoule** [comment]
It would be an option in the right-click menu to force the BPM output to be in CV mode when the BPM input is in external-clock mode, and it would provide a neat way to convert a clock signal into a CV that is proportional to the clock frequency, and I see that it could indeed have uses. The menu in Clocked is already quite loaded, and I can't promise it without first looking into the code, but I'll definitely consider the suggestion.

**Comment by jpnielsen** [comment]
👍 I don't know of a standard for CV BPM in VCV - perhaps Impromptu are the only modules that use it. (or my module knowledge is limited)

**Comment by MarcBoule** [comment]
There actually is a standard in VCV for this, and I follow that standard. Here it is if ever you are curious, it's part of this section:

https://vcvrack.com/manual/VoltageStandards#Pitch-and-Frequencies

**Comment by MarcBoule** [comment]
I've added this option, if ever you still need it and you would like a build to try it out, just let me know what platform you use. Cheers!

![image](https://user-images.githubusercontent.com/33604154/145418106-9356d89f-d9fb-464a-8d6a-4b8b7221b85e.png)

**Comment by jpnielsen** [comment]
Thank you, that was quick.

I will try it - I built from your github.

<img width="677" alt="image" src="https://user-images.githubusercontent.com/27916597/145437562-a7671cdf-2732-4321-acec-55ec9dcc3a7d.png">

**Comment by MarcBoule** [comment]
Excellent! Nice blank panel too :-)

**Comment by jpnielsen** [comment]
I cloned your blank panel and made that - It's not release ready.
Eventually, I would like it to load all svg's from a dir - and select the svg to  display using a CV and a trigger.
But I'm a C++ novice - So I might never finish it.

The santa plugin for windows is here
https://github.com/jpnielsen/vcv-plugins

Thank you for sharing your code.
