### ISSUE TITLE
Clocked: close all gates when Run is turned off.

### ISSUE THREAD

**Issue by MarcBoule** [MarcBoule/ImpromptuModular#48]
I know this item is closed, but is this applicable to Clocked? I'd like to have Clocked close all gates when Run is turned off, without triggering a reset, which throws off some sequencers. So basically, a "Gates close on Run Stop" mode. Then throw in a "Reset on Run Start" and you've basically got the all the scenarios covered where Clocked could play nice with every sequencer without having to use other modules as workarounds.  It's otherwise perfect, but those two options would really make it my ideal clock.

_Originally posted by @FunkybotsEvilTwin in https://github.com/MarcBoule/ImpromptuModular/issues/47#issuecomment-518022689_

**Comment by MarcBoule** [comment]
Hi @FunkybotsEvilTwin, Thanks for the suggestion, I will ponder this and get back to you, since making this sort of change without breaking patch compatibility in existing patches deserves more thought on my part. Cheers!

**Comment by MarcBoule** [comment]
https://community.vcvrack.com/t/clocks-gates-or-triggers/5143/12

**Comment by MarcBoule** [comment]
Although these menu labels are not exactly like you suggested, I think it covers all those cases you mention and gives the required flexibility:

![image](https://user-images.githubusercontent.com/33604154/62536730-b06c6680-b81c-11e9-9a80-01053178bec8.png)

If ever you're interested in testing it out, please let me know and I will post builds in the releases section.

**Comment by FunkybotsEvilTwin** [comment]
Hi Marc, sounds great! I'd definitely like to check it out if you can post a build. Thanks!

**Comment by MarcBoule** [comment]
Ok, I put up Mac and Win builds here for you to try:
https://github.com/MarcBoule/ImpromptuModular/releases/tag/v1.1.2a

**Comment by Eurikon** [comment]
Thanks Marc for making these changes,  I do like it as well! 
Latif

**Comment by FunkybotsEvilTwin** [comment]
Hi Marc, is it expected that the "Send reset pulse when restart" works in tandem with "Reset when run is turned off." You can't have the former without the latter. 

Also, I might be doing something wrong, but where I'm still seeing issues are with the Hora Drum Sequencer, which doesn't appear to be registering the reset pulse on run. Valley Topograph which also tends to go out of sync some of the time.  I think both are expecting a Reset on run to set their internal sequencers to beat 1, but neither seems to register the pulse.

Like, looking at the Hora Drum Sequencer, I'm running the Reset from Clocked to Reset in of the Drum Seq, Run to Run, Clock to Click. Using a basic 4 on the floor kick pattern with a syncopated hat. Hit Run and the first beat gets skipped on occasion. Hit Reset on Clocked and the kick immediately triggers every time. 

Topograph seems improved with this newest Clocked build, but can still drop beats.

**Comment by MarcBoule** [comment]
For Hora Drum seq, the way it is designed seems to be that when it gets a reset it plays step 1, and then the next clock is sees will advance and play step 2. But if we turn off run (and a reset goes out), then wait, then turn on run again, it will always play starting in step 2. 

This is why to play properly with run buttons, sequencers should have run inputs. I have more information on this in my manual, but not many sequencer makers are into this kind of detail. I have made my sequencers work properly with Clocked, if that helps, but agree that it should ideally work with others as well. 

To make it work with Hora, I would need to send the pulse when run turns on, not off, like you mention in you message above, but everyone integrating with a DAW seems to have requested that a reset goes out when we turn run off. Perhaps another choice should be offered for that. This is getting complicated! :-) 

So: "Restart when run is turned ON" instead of "OFF"... More thinking then, it would seem...

P.S. When you say you are connecting Run from Clocked to Run on Hora Drum seq, which one is the run input on Hora?

**Comment by FunkybotsEvilTwin** [comment]
FYI - just to add, the trick of connecting Clocked's Run output to it's own Reset input works for Hora. Topograph seems to behave a lot better at 24PPQ. At 4PPQ, the timing seems more suspect.

**Comment by FunkybotsEvilTwin** [comment]
> P.S. When you say you are connecting Run from Clocked to Run on Hora Drum seq, which one is the run input on Hora?

The play/pause input on the Hora drum seq. That's the one I'm connecting to.

**Comment by FunkybotsEvilTwin** [comment]
In my head, I'm kind of imagining a "Master Clocked." I'm picturing a version of clocked with:

1. All the existing run/reset options
2. Reset on Run (for Hora) and
3. Constant (or Steady) clock mode (for syncing delay effects without artifacts)

Now that just sounds like two new options, what's so great about that? Well...

4. You allow each Clock Output to run using the various options so Output 1 could by my Steady Clock Output that never resets, Output 2 to could Reset On Run for Hora, Output 3 could have the default settings that work so well with the Impromptu sequencers. 

How could you manage that visually? Well...

5. Via a sub-menu dropdown. So right-clicking on the GUI opens up the menu, and the difference is now there are menu options for each output. Clicking the Output brings up a sub-menu where you can change settings on a per-output basis.

6. Maybe you even make it bigger and include more multipliers. Forget about that guy who said Clocked was too small. When you need to run multiple clocks and can't keep your projects in sync, who cares about module size?

Now, is this overkill? Could be. But as evidenced here, there's a use case for it. Could this confuse newbies? Doesn't everything relating to modulars confuse newbies? Would you be willing to pay for that? Who, me? Yes, I would. A single clock module that can be daisy chained if needed and keep my entire project in perfect sync after some initial configuration would easily be worth $20 to me.

**Comment by MarcBoule** [comment]
Thanks for that detailed list, you've been thinking a lot about this! It will be useful in the next Clocked, but for now the most I can offer is to implement your point 2, like this: 

![image](https://user-images.githubusercontent.com/33604154/62625103-900edb80-b8f2-11e9-84f7-292a790a3c9d.png)

Builds have been updated in github if you would like to test it, it would be very much appreciated.

**Comment by FunkybotsEvilTwin** [comment]
Thanks Marc, this looks like it should do the trick. Now I can just daisy-chain a few instances of Clocked and should be able to keep just about any sequencer in sync. I'll check it out later today and let you know if I run into trouble. Thanks for the quick turnaround on these!

**Comment by FunkybotsEvilTwin** [comment]
Marc, just wanted to write back to let you know that this version has everything running in sync over here. I'm triggering a Hora Drum Seq, Topology, Seq-3, and Phrase-Seq 16 from two instances of clocked and everything's starting exactly where it should. Can't thank you enough for your attention to this!

**Comment by MarcBoule** [comment]
Excellent, thanks for the positive feedback! I'll close this issue now, and the new version will be part of the next update I make in a a few weeks. Cheers!
