### ISSUE TITLE
Gate-Seq-64 (v0.6.4): no enough time to change probability via encoder

### ISSUE THREAD

**Issue by DomiKamu** [MarcBoule/ImpromptuModular#5]
Hi Marc,

About Gate-Seq-64, please give more delay to change probability, the current delay is very (too) short when you click on step to have a chance to change probability via SEQ# encoder.

Of course you'll can consider this for future release (aka: not urgent). We'll can talk together via Messenger if you want.

Thanks in advance.

Dominique.

**Comment by DomiKamu** [comment]
The delay is too short as long as you don't have a Core Audio module (correctly routed to physical interface), this delay is 1.5 second (too short) - instead of 3 seconds (it's okay).

OS: Windows 7 Pro SP1 64-bit

**Comment by MarcBoule** [comment]
Thanks for the feedback Dom! Indeed, it was issue 919.
https://github.com/VCVRack/Rack/issues/919
I bumped it up to 3 seconds (initially I had 2.5 seconds), and I have added a mention of this issue in my readme, so at least it's documented. Cheers!
