### ISSUE TITLE
Derivative Work: GateSeq192

### ISSUE THREAD

**Issue by VegaDeftwing** [MarcBoule/ImpromptuModular#52]
Hello there! I wanted to make a module that allowed for sequencing tuplets and even nested tuplets so started on a derivative of GateSeq64 and threw this together:
![2022-05-16-190433_1458x1543_scrot](https://user-images.githubusercontent.com/11283620/168702266-c4631abe-871d-4d56-902b-471aed1431d6.png)
Where the sequence is best thought of 16 steps with 12 sub-steps each, running vertically. The Cyan lines being triplets, and so on. This is exceptionally fun to play with but I fear that despite my best intentions it's not quite visually distinct enough from your modules. So, while I could continue development and alter the style to make it visually distinct I thought I'd see if you'd just like to take it over and make it an official Impromptu module instead?

What are your thoughts?

**Comment by MarcBoule** [comment]
Hi Vega, that's quite the array of LED buttons :-) I see where you are going with this, and although I can see the utility of the idea, I don't think I will be in position to continue it, so please feel free to continue it as you please. I think it would not be too hard to alter the style to make it different from the Impromptu series, just changing the font and those gray boxes would go a long way I think, and the components are stock Rack components, so no need to change those. Cheers!

**Comment by VegaDeftwing** [comment]
![image](https://user-images.githubusercontent.com/11283620/171967584-5cf9d334-15d5-4138-a130-311e828448ea.png)

Nobody accused me of being a graphic designer, but I don't think I can make it much more different than this without significantly more work. If you're cool with this, I'll (slowly) work on finishing up the modifiations to the code and then probably release it as it's own collection on the library.

**Comment by MarcBoule** [comment]
Sure, no problem! Have fun :-)
