### ISSUE TITLE
Is it possible to add the ability to set a BPM low as zero in Clocked and derivatives?

### ISSUE THREAD

**Issue by pgatt** [MarcBoule/ImpromptuModular#56]
A couple of times now I have reached for other clock modules (gasp) because I wanted things to start from silent and ramp up to a target BPM. 

If this breaks compatibility with existing patches, is it possible to add a right-click menu option such as "Enable zero BPM" and the BPM dial changes limits only when that is set to true, leaving existing patches with the current default behaviour?

**Comment by MarcBoule** [comment]
Hi Paul,
Unfortunately I will not be adding the 0 BPM option to Clocked, but thanks for the suggestion. I really want to keep things stable with this module, and with all the other modules I'm working on, my head is just not into opening up that code and messing with it.
Hope you'll understand.
Cheers,
Marc

**Comment by pgatt** [comment]
Hi Marc,

Absolutely no problem at all, I understand completely, thanks for considering.
