### ISSUE TITLE
Color Coding makes visibility difficult for the color-challenged

### ISSUE THREAD

**Issue by TantalusVCV** [MarcBoule/ImpromptuModular#58]
Greetings and thanks for the awesome VCV Rack modules you've created!  I am really enjoying Foundry and the other related sequencer products, but because I am color challenged (partially colorblind) I find that many of the visual cues which rely on distinguishing one color from another are not accessible to me without great difficulty if at all.  It would be great to have an interface that didn't rely on color changes/differences to convey critical information.  In particular, the rows of "LEDs" all next to each other are very confusing to me, as the best I can do is tell that some are not as bright as others.  Any colored light indicator (unless it's simply on or off) is similarly difficult.  Sometimes even on/off transitions are not clearly distinguishable because of lack of contrast with the background.
It occurs to me that the best solution would probably be to have an alternate interface which was high contrast or used shapes instead of colors, and to let the user select that option in the right-click menu.  That way the change would not impact those with normal vision, but would be available for those with color distinction difficulties.
Thanks for listening, and keep up the great work!!

**Comment by MarcBoule** [comment]
Hi Tantalus,

You're not the first person to mention this. You might want to check out this little known feature I added for color-challenged adapations, it's not the most polished solution, but with a little tweaking of the RGB values on your part, perhaps your can improve things. I hope the content posted in this issue here will help you:

https://github.com/MarcBoule/ImpromptuModular/issues/46

Cheers!

Marc

**Comment by MarcBoule** [comment]
Also, you're likely already doing this, but I would also recommend perhaps using the dark theme (in the module' menus) and setting contrast to make the panel as dark as possible, thus better showing the LEDs' colours.
