### ISSUE TITLE
Gate Seq and phrase seq won't copy pattern

### ISSUE THREAD

**Issue by dinegredin** [MarcBoule/ImpromptuModular#61]
Hello,
It seems that the copy fonction from a pattern to another on the Sequencers doesn't work.
I've tried the Gate Seq and phrase 16 for instance, it's the same issue for both.
I've tried on the cardinal native and VCV rack 2Free on Mac.

**Comment by dinegredin** [comment]
I forgot to thank you first for your wonderful collection of module....
je les adore !!!

**Comment by MarcBoule** [comment]
Merci! Yes, the copy-paste feature on those sequencers does not use the clipboard, so unfortunately you can't go from one to the other. But in the PhraseSequencers at least (and Foundry, but not GateSeq64), you might have success using the portable sequence copy-paste located here in the menus, for example:

![image](https://user-images.githubusercontent.com/33604154/211698498-e2005040-c512-4ad9-9936-3d31163f36d6.png)

this does use the clipboard and might do the trick.
