### ISSUE TITLE
Feature request: Clock-Phase signal expander for Clocked/Clockd

### ISSUE THREAD

**Issue by Setkias** [MarcBoule/ImpromptuModular#62]
Hi Marc,

Would it be possible to have an expander with three Clock-Phase signals outputs on Clocked/Clockd?

Some argumentation for this feature request can be found in this thread:  https://community.vcvrack.com/t/bpm-voltage-standard/19170/15 

D.

**Comment by MarcBoule** [comment]
Hi Dan,

I've been following that discussion, but I don't think I will be opening that can of worms :-) Not that it isn't interesting of course, just that it's not something I have the energy to get into. There are a lot of strings attached to this idea, and to keep my set of modules consistent and not open up a bunch of support issues and such, I will prefer to keep things as they are. 

If we were to bring back time to 5 years ago when I coded my first module for Rack, things might be different, but at this stage I'm going to perfer to opt out. But the idea is there in my head, and so it's not impossible one day I would do somehting with phased clocks, but not in the short term and likely not with my existing Impromptu set.

Thanks to you (and Lars) on the forum for reaching out! 

Cheers,

Marc

**Comment by Setkias** [comment]
I completely understand. Your clocks and sequencers form indeed a consistent collection and who likes worms eh?
