### ISSUE TITLE
Using CV to change sequence # in Foundry-X

### ISSUE THREAD

**Issue by LapinLaid** [MarcBoule/ImpromptuModular#66]
I assumed that for every semi-tone increment I would get a seq# increment but instead it only changes on white notes. Is there a reason or is it a bug ?

**Comment by MarcBoule** [comment]
Just to make sure, have you set the "Seq CV in level" to "C2-D7#"? Since from a quick test on my side, it seems to be working correctly:

![image](https://user-images.githubusercontent.com/33604154/227945109-bda54981-1d47-4fe1-8e4f-c411267acfff.png)

**Comment by MarcBoule** [comment]
In the picture above, I'm selecting the 4th semitone on TwelveKey, and in this one, the 7th:

![image](https://user-images.githubusercontent.com/33604154/227945409-40c3b4f1-4477-4e44-b6b7-a4739b01d7ca.png)

**Comment by LapinLaid** [comment]
Sorry it’s my fault ☹ I was in 0-10V mode! I’m relatively new to VCV and  wasn’t aware of that option. Thanks for the quick reply 😁

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : Marc ***@***.***>
Envoyé le :27 mars 2023 08:53
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [MarcBoule/ImpromptuModular] Using CV to change sequence # in Foundry-X (Issue #66)


Just to make sure, have you set the "Seq CV in level" to "C2-D7#"? Since from a quick test on my side, it seems to be working correctly:

[image]<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F33604154%2F227945109-bda54981-1d47-4fe1-8e4f-c411267acfff.png&data=05%7C01%7C%7C5b871bd299184e73a99708db2ec23591%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638155183877767614%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=klteC4l0VDKQQTouxlyq7Zvyl2t6u9m91hIDRolW5JY%3D&reserved=0>

**Comment by MarcBoule** [comment]
Aucun problème :-)

**Comment by LapinLaid** [comment]
J’ai parlé en anglais à un francophone 😯🙄
Quelle honte 😂😂


Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : Marc ***@***.***>
Envoyé le :27 mars 2023 09:14
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [MarcBoule/ImpromptuModular] Using CV to change sequence # in Foundry-X (Issue #66)


Aucun problème :-)

**Comment by MarcBoule** [comment]
Haha, pas de soucis!  C'est vrai qu'il n'y a pas mon accent sur mon nom (Boulé) dans mon handle github ;-)

Salutations de Montréal!

**Comment by LapinLaid** [comment]
Et en plus on est voisins 😃
Salutations de Pointe-aux-Trembles!

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : Marc ***@***.***>
Envoyé le :27 mars 2023 11:30
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [MarcBoule/ImpromptuModular] Using CV to change sequence # in Foundry-X (Issue #66)


Haha, pas de soucis! C'est vrai qu'il n'y a pas mon accent sur mon nom (Boulé) dans mon handle github ;-)

Salutations de Montréal!
