### ISSUE TITLE
Static analysis issues

### ISSUE THREAD

**Issue by cschol** [MarcBoule/ImpromptuModular#68]
Marc,
as part of the integration process we now run CodeQL and cppcheck.

CodeQL issue found:
```
"Multiplication result converted to larger type","A multiplication result that is converted to a larger type can be a sign that the result can overflow the type converted from.","warning","Multiplication result may overflow 'int' before it is converted to 'uint64_t'.","/src/FoundrySequencerKernel.cpp","587","2
4","587","53"
```

cppcheck issues found:
[cppcheck-results.log](https://github.com/MarcBoule/ImpromptuModular/files/12340731/cppcheck-results.log)

Take a look (specifically the cppcheck ones with out of bounds access) and see if any of these should be fixed. Thanks.

**Comment by MarcBoule** [comment]
Thanks for pointing those out, I hopefully have fixed them all.
Cheers,
Marc
