### ISSUE TITLE
Clocked drifts over time

### ISSUE THREAD

**Issue by pronvit** [MarcBoule/ImpromptuModular#69]
The remainder that you calculate here https://github.com/MarcBoule/ImpromptuModular/blob/master/src/Clocked.cpp#L71 is lost when you call `reset()` and then `start()` on the master clock, causing all iterations except the first one to take a bit longer than needed, and this error accumulates over time.

**Comment by MarcBoule** [comment]
Ok, I'll try and take a look within the next week or so.

**Comment by MarcBoule** [comment]
This should now have been fixed in the last commit, thanks for raising the issue! If you see it not behaving well, please let me know.
Cheers,
Marc
