### ISSUE TITLE
4view feature request or for separate module

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/ImpromptuModular#7]
Hi Marc! Just got an instant idea about Chord Tuner or Chord Recognizer module. What do you think is it possible in terms of using 4view for this or building another module for it (of course if you have any curiosity in it)? It could be useful for the people who would like to learn a theory by just playing and also knowing what chord or scale he\she likes to use for expanding his\here musical knowledge \ or for just other funny things. Cheers!

**Comment by MarcBoule** [comment]
Hi Artem, do you mean something that takes an audio signal and extracts the chord names, or it takes instead the pitch CVs and shows the chord names?

**Comment by vcvrackideas** [comment]
> Hi Artem, do you mean something that takes an audio signal and extracts the chord names, or it takes instead the pitch CVs and shows the chord names?

No I meant CV pitch poly input that takes the input for example from your awesome CHORD-KEY) and yeah that shows the chord names. 
An audio input that can recognize chords...it's like a rocket science I think) very complicated I think

**Comment by MarcBoule** [comment]
Ok, it's definitely more doable in CV than in audio, agreed! It would likely have to be a separate module though. I've put it in my list of things to make, but can't promise when I'll get to it.

**Comment by MarcBoule** [comment]
I ended up being able to squeeze it into FourView, here's how it looks:

![image](https://user-images.githubusercontent.com/33604154/77125174-6c307e00-6a1b-11ea-98ce-2bc921b50448.png)

I'll be submitting it soon to the library, but if you try it and have any comments, please let me know asap. Thanks again for the suggestion Artem!

**Comment by vcvrackideas** [comment]
thanks! and that's pretty interesting. I chose another chord module in vcv (aaron static) and try to achieve same chords and connected it two different plaits instances, and while chord tuners show the same chord they sounded differently. Here is the screenshot and the patch, don't know what's exactly the difference but looks interesting. Also tested hampton harmonics sequencers but this is not correspond to the chord tuner and aaron static chord module at all especially in Csus2\Csus4 and things like that. 
[4viewtest.zip](https://github.com/MarcBoule/ImpromptuModular/files/4358197/4viewtest.zip)
![2020-03-20_09-27-42](https://user-images.githubusercontent.com/42435368/77141375-c2d6a000-6a8d-11ea-8e79-77c091dec520.png)

**Comment by vcvrackideas** [comment]
Ok, I think I solved it. The reason was in poly cv output of CHORD-KEY - even if the last 4th note is in the -- -- state the output of 4th mono out in poly cable is still here. So I just back to the right click options and chose 3 cv out and now modules generate same sound. Also realized how's Hampton works - it always send 4 notes so only signal manifold from count modula would help.
But I'm here with the suggestion again) What about 4view would received poly signal to the first input and also shows the info about the chord? I tested that and it seems it's only work for 3x mono inputs from 3rd party modules. I don't think it's necessary just because other chord modules show us already what kind of chord it is but who knows - it maybe useful for polyphonic output of random modules passed through quantizer?) That would expand a bit more potential of this magical mini info module. Thanks again for implementing the tuner Marc!)

**Comment by MarcBoule** [comment]
> What about 4view would received poly signal to the first input and also shows the info about the chord?

I did implement this, but I figured that it might cause some conflicts so I put an option in the right-click menu to enable it (off by default). If you think it's pretty safe to have it on all the time, just let me know and I'll consider making that option active by default :-)

**Comment by vcvrackideas** [comment]
No, sorry didn't notice this before. This is pretty much solved and actually no reasons to do that as main option. Cheers!

**Comment by MarcBoule** [comment]
Thanks, Cheers!
