### ISSUE TITLE
build failure because of missing type specifier

### ISSUE THREAD

**Issue by modphon** [MarcBoule/ImpromptuModular#72]
Building commit d8c9975 with Rack toolchain (at least for mac-x64) fails with the following error:

src/ImpromptuModular.hpp:63:8: error: a type specifier is required for all declarations
inline calcRGOR(int retrigGatesOnReset, Input* runInput) {
~~~~~~ ^

This can be fixed adding ‘bool’ so that line 63 of src/ImprompuModular.hpp begins ‘inline bool calcRGOR(…)’.

**Comment by MarcBoule** [comment]
Thanks! Amazing how my compiler didn't flag this...
