### ISSUE TITLE
Why was SMS16 deprecated?

### ISSUE THREAD

**Issue by flarn2006** [MarcBoule/ImpromptuModular#74]
I liked that module; why deprecate it if there's no direct replacement?

Here's a saved selection for anyone who wants it: [sms16.zip](https://github.com/MarcBoule/ImpromptuModular/files/14350322/sms16.zip)

**Comment by MarcBoule** [comment]
Hi, you can find the reasoning for this in the community post I made [here](https://community.vcvrack.com/t/impromptu-modular-announcement-and-discussion-thread/1694/49). In short, I find it kind of redundant now, and can be replaced with only a few modules and quick patching, and it was also made at a time before we had the possibility of saving subsets of patches as _VCV Selections_.

**Comment by flarn2006** [comment]
Alright, thanks for the explanation. If it were up to me, I'd keep it, because it's a neat little all-in-one unit where everything can be in one loadable preset, plus there's something I just like about messing around with it, wiring it in different ways. But it's your plugin, so it's up to you.

**Comment by dromer** [comment]
Oof this is a shame. I was looking to update Impromptu in Cardinal, but not being backwards compatible is really not good.

I actually used this module quite regularly and this would basically break older projects.

We may need to fork your repo to reintroduce it ..

**Comment by MarcBoule** [comment]
Sorry, I really will try to not do this to any more modules, but this module in particular used a ton of old code from the 0.6 days of the Fundamental modules, and I really did not have the energy or time to update it to the newer code. Feel free to fork if needed, as you say.

**Comment by dromer** [comment]
Well one major goal with Cardinal is to provide backwards compatibility.
A user should be able to open an old project without issues.

Therefore if we want to update to your latest code it will unfortunately require us to fork and provide this older module.

We have seen other plugins deprecate modules, but simply hide them from the manifest (ie BaconPlugs did this with the 303 module).

I don't know the details, but I guess you changed some things in your internal dependencies that would be incompatible?

**Comment by MarcBoule** [comment]
> I don't know the details, but I guess you changed some things in your internal dependencies that would be incompatible?

Not even, I just decided I didn't want the bloat in my plugin, it's crazy, but the code and the SVG, for a module that I didn't like nor want to support anymore, with lots of dsp code I didn't write, I just didn't want it anymore. I realize what this involves for users, and that it's really not good practice, but for me the removal was done for the good/consistency/quality of my plugin. Hope this is understandable :-)

**Comment by dromer** [comment]
Yeah I guess. Wish you made that decision before we added the plugin to Cardinal ;)

Hopefully we won't have an issue syncing with your repo in the future. For now I'm putting the update on pause until we have a plan on how to best move forward.

Thnx for the quick response!
