### ISSUE TITLE
Sequencer octave button tooltips are reversed

### ISSUE THREAD

**Issue by flarn2006** [MarcBoule/ImpromptuModular#75]
The octave buttons go from 7 to 1 in descending order from top to bottom, and are labeled accordingly. However, I noticed that when I put the cursor over them, it goes "Octave 1", "Octave 2", etc. where it should say "Octave 7", "Octave 6" and so on. Just a slight nitpick but thought you might want to be aware of it.

**Comment by MarcBoule** [comment]
Indeed, nice catch, I'll fix this for the next release. Thanks for reporting it.

**Comment by MarcBoule** [comment]
new version now in the library, closing
