### ISSUE TITLE
Gate-seq-64 steps get edited when dragging cables over the window

### ISSUE THREAD

**Issue by dustractor** [MarcBoule/ImpromptuModular#76]
It took me a while to figure out why sometimes when I would make a sequence in Gate-seq-64, later on I would find stray extra steps added or removed when I was sure I had not interacted with the module.  At first I thought it was just happening randomly but eventually I realized it was from when I had been dragging cables and my mouse crossed over it.  If the last action was to toggle a step on, then the drag will also toggle steps on, and vice versa such that if the last action was to toggle a step off, then dragging over the interface will toggle steps off.

https://github.com/MarcBoule/ImpromptuModular/assets/515818/0b547d46-3a58-48b0-aa90-ef90fecbeb6a

**Comment by MarcBoule** [comment]
Excellent find, the video makes it perfectly clear, I'll take a look!

**Comment by MarcBoule** [comment]
Fixed; here are new builds if ever you want to test or use it.

https://github.com/MarcBoule/ImpromptuModular/releases/tag/v2.4.2b

Thanks for the bug report!

**Comment by dustractor** [comment]
New update works great, btw!
