### ISSUE TITLE
Use Rack Global Theme currently not working

### ISSUE THREAD

**Issue by RubyRezal** [MarcBoule/ImpromptuModular#79]
VCV Rack Free 2.5.2
Impromptu 2.5.0

Currently while an Impromptu module Panel theme is set to "Use Rack global theme" it only shows the light theme regardless of the global theme setting. To get the dark theme I have to manually disable this and select the dark them on each Impromptu module.

So far I've only tried Clocked and Gate-Seq-64

**Comment by RubyRezal** [comment]
Found this toggle at the bottom of the View menu. 
![image](https://github.com/user-attachments/assets/742cc499-0897-47ef-ba01-7d559b00b739)

Enabling it seems to force all modules to display dark panels regardless of the global theme. I guess that effectively solves the issue?

Sorry, I'm a newbie and this could just be me not understanding how the global theme works.

**Comment by MarcBoule** [comment]
Yes, exactly. The Theme controls only the background in Rack (rails, etc), it is actually the Dark panels setting that controls the modules' colours.

<img width="565" alt="image" src="https://github.com/user-attachments/assets/ddf0bc76-b4be-4b0b-8b4f-922b86c4d72f">

**Comment by MarcBoule** [comment]
No worries, you're not the first to have confused those two settings in Rack! :-)
Cheers,
Marc

https://github.com/MarcBoule/ImpromptuModular/issues/77

**Comment by RubyRezal** [comment]
Thank you for verifying.  Seems a bit counterintuitive, but if that's the way it is then I understand now.
