### ISSUE TITLE
CLKD tooltips 

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/ImpromptuModular#8]
Hi Marc. I've noticed that tooltips in the CLKD show incorrect values according to display, always showing more at one step ratio.

**Comment by MarcBoule** [comment]
Hi Artem, indeed, it shows the index of the ratio, which is an internal value, but not very insightful for the users. I have fixed this in my latest source code, so if ever you are building plugins, just pull the latest version and it will be fixed for you, else it will be part of my next update in the library. Thanks for mentioning it! Cheers :-)

**Comment by MarcBoule** [comment]
Fixed for the next version.
