### ISSUE TITLE
Quantizer expander based on CHORD-KEY state

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/ImpromptuModular#9]
Hi Marc! Just got an idea on quantizer (as expander) that could be based on the notes that are currently present in CHORD-KEY instance. This would be useful to follow the chord progression that programmed in CHORD-KEY current state. And then we just can apply side sequencers to get an additional voices without messing with sequential switches to extract the right sequence for an each new voice in the patch.

**Comment by MarcBoule** [comment]
Not sure I follow you completely. So the expander would be a quantizer, with a CV in and a CV out, and it would quantize the input to the nearest of the 4 notes that are selected in CHORD-KEY? And changing the index would change the quantization as expected?

**Comment by vcvrackideas** [comment]
> Not sure I follow you completely. So the expander would be a quantizer, with a CV in and a CV out, and it would quantize the input to the nearest of the 4 notes that are selected in CHORD-KEY? And changing the index would change the quantization as expected?

Yes Marc, exactly what you've described! Btw personally I like rewin 4x in\outs and octave switches but firstly I just curious are you have any interest in that idea?)

**Comment by MarcBoule** [comment]
I'll have to think about it, but I can understand why it could be useful. :-)

**Comment by vcvrackideas** [comment]
Just for me the chord-key can easily become the core pitch module for the whole patch and tools like an quantizer expander could be pretty useful to create nice sequences around the chords

**Comment by MarcBoule** [comment]
Ready to test if you want Artem, if you type "chord-key" in the module browser, you will see CHORRD-KEY and its expander (names CHD-X in the panel, but we can't search the module with that name). Let me know if you see anything not working as expected. The expander has to be placed to the right of CHORD-KEY. We can even then put 4-VIEW to the right of the expander to see the note names as before.

**Comment by vcvrackideas** [comment]
Should I say that you've just made a super awesome little thing with unbeliveable potential?) Thanks Marc, that's definitely what I was looking for. Appending a quick patch with it (hope you have lindgerberg, count and stoermelder collections as well). 
So I believe the final "chord" you can make in this module (of course if you don't have any other aces in your magical dev sleeves)) is adding UP DOWN NEAREST mode of quantizers in right-click\front panel for an each quantizer in\out. 
And wow I've just realized that 4view can be used as a food for sequential switches or actually a polysplitter for the chord-key.

[chd-x test.zip](https://github.com/MarcBoule/ImpromptuModular/files/4316391/chd-x.test.zip)

**Comment by vcvrackideas** [comment]
Just got an instant idea on adding ability to quatizing to intervals (like in ENERGY for example, fifths or something) but with some special chord it may be an atonal one so the potential users should control his sequencer more and it's not quite fun. 
Also got an idea on poly inputs in quantizer but still don't have a strong point to suggest it. Maybe as linking of two chord-key instances but how and why - still don't understand some of my thoughts)

**Comment by MarcBoule** [comment]
Nice, really cool patch, thanks for sharing it :-) 

1) I thought about UP/DOWN/NEAREST, but I noticed VCV QUANTIZER doesn't have it (and I used Andrews code), and so I could look to perhaps add it, but what purpose does it really serve? I have always just used NEAREST anyways myself.

1) Not sure I want to go to intervals

1) The quantizers in CHD-X are polyphonic by the way, although you perhaps had something more complicated in mind, but as it is now, you can feed a poly signal and it will quantize each channel in that signal

Cheers Artem, and thanks for testing it out!

**Comment by vcvrackideas** [comment]
UP/DOWN/NEAREST just for the variation of the same sequence. But it doesn't worth of changing the code really. I can simply add another sequence or copy existed and change some voltages) So it's ok. 
In that way I think everything is ready to release at least from the user point. Thanks and Cheers Marc!

**Comment by MarcBoule** [comment]
All good, thanks man!
